import type { CircuitDetailsProps, ContinentProps } from 'types/circuits';

export const CONTINENTS: ContinentProps = {
    'North America': { center: [-100, 40], zoom: 3 },
    'South America': { center: [-60, -15], zoom: 3 },
    Asia: { center: [100, 40], zoom: 3 },
    Australia: { center: [135, -25], zoom: 4 },
    Europe: { center: [10, 50], zoom: 4 },
};

export const CIRCUIT_DETAILS: CircuitDetailsProps = {
    austin: {
        altitude: 130,
        bbox: [-97.643463, 30.130031, -97.624458, 30.139453],
        circuitType: 'RACE',
        country: 'united-states-of-america',
        firstgp: 2012,
        full_name: 'Circuit of the Americas',
        id: 'austin',
        latitude: 30.1328,
        length: 5514,
        longitude: -97.6411,
        name: 'Austin',
        official_name: 'Circuit of the Americas',
        opened: 2012,
        place_name: 'Austin, Texas, United States',
        shortName: 'Austin',
        timezone: {
            name: 'America/Chicago',
            offset: -5,
            dst: true,
            start: {
                month: 3,
                day: 8,
                hour: 2,
            },
            end: {
                month: 11,
                day: 1,
                hour: 2,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Circuit_of_the_Americas',
    },
    bahrain: {
        altitude: -16,
        bbox: [50.510278, 26.026086, 50.518387, 26.036885],
        circuitType: 'RACE',
        country: 'bahrain',
        firstgp: 2004,
        full_name: 'Bahrain International Circuit',
        id: 'bahrain',
        latitude: 26.0325,
        length: 5412,
        longitude: 50.5106,
        name: 'Sakhir',
        official_name: 'Bahrain International Circuit',
        opened: 2002,
        place_name: 'Sakhir, Bahrain',
        shortName: 'Bahrain',
        timezone: {
            name: 'Asia/Bahrain',
            offset: 3,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Bahrain_International_Circuit',
    },
    baku: {
        altitude: -25,
        bbox: [49.830927, 40.362639, 49.855189, 40.376148],
        circuitType: 'STREET',
        country: 'azerbaijan',
        firstgp: 2016,
        full_name: 'Baku City Circuit',
        id: 'baku',
        latitude: 40.3725,
        length: 6003,
        longitude: 49.8533,
        name: 'Baku',
        official_name: 'Baku City Circuit',
        opened: 2016,
        place_name: 'Baku, Azerbaijan',
        shortName: 'Baku',
        timezone: {
            name: 'Asia/Baku',
            offset: 4,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Baku_City_Circuit',
    },
    catalunya: {
        altitude: 165,
        bbox: [2.252134, 41.564187, 2.263669, 41.574752],
        circuitType: 'RACE',
        country: 'spain',
        firstgp: 1991,
        full_name: 'Circuit de Barcelona-Catalunya',
        id: 'catalunya',
        latitude: 41.5697,
        length: 4655,
        longitude: 2.2611,
        name: 'Barcelona',
        official_name: 'Circuit de Barcelona-Catalunya',
        opened: 1991,
        place_name: 'Montmeló, Barcelona, Catalonia, Spain',
        shortName: 'Barcelona',
        timezone: {
            name: 'Europe/Madrid',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya',
    },
    hungaroring: {
        altitude: 239,
        bbox: [19.242326, 47.577571, 19.256609, 47.588474],
        circuitType: 'RACE',
        country: 'hungary',
        firstgp: 1986,
        full_name: 'Hungaroring',
        id: 'hungaroring',
        latitude: 47.5789,
        length: 4381,
        longitude: 19.2486,
        name: 'Budapest',
        official_name: 'Hungaroring',
        opened: 1986,
        place_name: 'Mogyoród, Hungary',
        shortName: 'Budapest',
        timezone: {
            name: 'Europe/Budapest',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Hungaroring',
    },
    imola: {
        altitude: 47,
        bbox: [11.702032, 44.336508, 11.725155, 44.345054],
        circuitType: 'RACE',
        country: 'italy',
        firstgp: 1980,
        full_name: 'Autodromo Enzo e Dino Ferrari',
        id: 'imola',
        latitude: 44.3439,
        length: 4909,
        longitude: 11.7167,
        name: 'Imola',
        official_name: 'Autodromo Enzo e Dino Ferrari',
        opened: 1953,
        place_name: 'Imola, Italy',
        shortName: 'Imola',
        timezone: {
            name: 'Europe/Rome',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari',
    },
    interlagos: {
        altitude: 765,
        bbox: [-46.700536, -23.706404, -46.694033, -23.696978],
        circuitType: 'RACE',
        country: 'brazil',
        firstgp: 1973,
        full_name: 'Autódromo José Carlos Pace - Interlagos',
        id: 'interlagos',
        latitude: -23.7036,
        length: 4309,
        longitude: -46.6997,
        name: 'Sao Paulo',
        official_name: 'Autódromo José Carlos Pace',
        opened: 1940,
        place_name: 'São Paulo, Brazil',
        shortName: 'Sao Paulo',
        timezone: {
            name: 'America/Sao_Paulo',
            offset: -3,
            dst: true,
            start: {
                month: 10,
                day: 1,
                hour: 0,
            },
            end: {
                month: 2,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace',
    },
    jeddah: {
        altitude: 12,
        bbox: [39.100858, 21.625359, 39.106552, 21.650116],
        circuitType: 'STREET',
        country: 'saudi-arabia',
        firstgp: 2021,
        full_name: 'Jeddah Corniche Circuit',
        id: 'jeddah',
        latitude: 21.6353,
        length: 6175,
        longitude: 39.1025,
        name: 'Jeddah',
        official_name: 'Jeddah Corniche Circuit',
        opened: 2021,
        place_name: 'Jeddah, Saudi Arabia',
        shortName: 'Jeddah',
        timezone: {
            name: 'Asia/Riyadh',
            offset: 3,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Jeddah_Street_Circuit',
    },
    'las-vegas': {
        altitude: 610,
        bbox: [-115.173015, 36.108017, -115.160217, 36.125492],
        circuitType: 'STREET',
        country: 'united-states-of-america',
        firstgp: 2023,
        full_name: 'Las Vegas Street Circuit',
        id: 'las-vegas',
        latitude: 36.1179,
        length: 6116,
        longitude: -115.1671,
        name: 'Las Vegas',
        official_name: 'Las Vegas Street Circuit',
        opened: 2023,
        place_name: 'Las Vegas, Nevada, United States',
        shortName: 'Las Vegas',
        timezone: {
            name: 'America/Los_Angeles',
            offset: -8,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 11,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Las_Vegas_Street_Circuit',
    },
    losail: {
        altitude: 130,
        bbox: [51.447494, 25.483835, 51.459956, 25.497115],
        circuitType: 'RACE',
        country: 'qatar',
        firstgp: 2012,
        full_name: 'Losail International Circuit',
        id: 'losail',
        latitude: 25.375,
        length: 5514,
        longitude: 51.2222,
        name: 'Losail',
        official_name: 'Losail International Circuit',
        opened: 2012,
        place_name: 'Losail, Qatar',
        shortName: 'Losail',
        timezone: {
            name: 'Asia/Qatar',
            offset: 3,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Losail_International_Circuit',
    },
    'marina-bay': {
        altitude: 18,
        bbox: [103.851563, 1.286566, 103.864425, 1.294899],
        circuitType: 'STREET',
        country: 'singapore',
        firstgp: 2008,
        full_name: 'Marina Bay Street Circuit',
        id: 'marina-bay',
        latitude: 1.2914,
        length: 4928,
        longitude: 103.8641,
        name: 'Singapore',
        official_name: 'Marina Bay Street Circuit',
        opened: 2008,
        place_name: 'Marina Bay, Singapore',
        shortName: 'Singapore',
        timezone: {
            name: 'Asia/Singapore',
            offset: 8,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit',
    },
    melbourne: {
        altitude: 10,
        bbox: [144.962138, -37.853926, 144.97859, -37.838005],
        circuitType: 'STREET',
        country: 'australia',
        firstgp: 1996,
        full_name: 'Albert Park Circuit',
        id: 'melbourne',
        latitude: -37.8497,
        length: 5278,
        longitude: 144.968,
        name: 'Melbourne',
        official_name: 'Albert Park Circuit',
        opened: 1953,
        place_name: 'Melbourne, Australia',
        shortName: 'Melbourne',
        timezone: {
            name: 'Australia/Melbourne',
            offset: 11,
            dst: true,
            start: {
                month: 10,
                day: 1,
                hour: 0,
            },
            end: {
                month: 4,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Albert_Park_Circuit',
    },
    'mexico-city': {
        altitude: 2232,
        bbox: [-99.09685, 19.397044, -99.083095, 19.40641],
        circuitType: 'RACE',
        country: 'mexico',
        firstgp: 1963,
        full_name: 'Autódromo Hermanos Rodríguez',
        id: 'mexico-city',
        latitude: 19.4039,
        length: 4304,
        longitude: -99.0907,
        name: 'Mexico City',
        official_name: 'Autódromo Hermanos Rodríguez',
        opened: 1962,
        place_name: 'Mexico City, Mexico',
        shortName: 'Mexico City',
        timezone: {
            name: 'America/Mexico_City',
            offset: -6,
            dst: true,
            start: {
                month: 4,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez',
    },
    miami: {
        altitude: 1,
        bbox: [-80.244805, 25.955259, -80.229711, 25.96059],
        circuitType: 'RACE',
        country: 'united-states-of-america',
        firstgp: 2022,
        full_name: 'Miami International Autodrome',
        id: 'miami',
        latitude: 25.9579,
        length: 5412,
        longitude: -80.2393,
        name: 'Miami',
        official_name: 'Miami International Autodrome',
        opened: 2022,
        place_name: 'Miami, Florida, United States',
        shortName: 'Miami',
        timezone: {
            name: 'America/New_York',
            offset: -5,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 11,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Miami_International_Autodrome',
    },
    monaco: {
        altitude: 47,
        bbox: [7.421216, 43.732362, 7.430363, 43.741114],
        circuitType: 'STREET',
        country: 'monaco',
        firstgp: 1929,
        full_name: 'Circuit de Monaco',
        id: 'monaco',
        latitude: 43.7347,
        length: 3337,
        longitude: 7.4206,
        name: 'Monaco',
        official_name: 'Circuit de Monaco',
        opened: 1929,
        place_name: 'Monte Carlo, Monaco',
        shortName: 'Monaco',
        timezone: {
            name: 'Europe/Monaco',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Circuit_de_Monaco',
    },
    montreal: {
        altitude: 13,
        bbox: [-73.52994, 45.49706, -73.521949, 45.514298],
        circuitType: 'STREET',
        country: 'canada',
        firstgp: 1978,
        full_name: 'Circuit Gilles-Villeneuve',
        id: 'montreal',
        latitude: 45.5017,
        length: 4361,
        longitude: -73.5228,
        name: 'Montreal',
        official_name: 'Circuit Gilles-Villeneuve',
        opened: 1978,
        place_name: 'Montreal, Quebec, Canada',
        shortName: 'Montreal',
        timezone: {
            name: 'America/Toronto',
            offset: -5,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 11,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve',
    },
    monza: {
        altitude: 142,
        bbox: [9.280697, 45.611858, 9.296856, 45.631364],
        circuitType: 'RACE',
        country: 'italy',
        firstgp: 1950,
        full_name: 'Autodromo Nazionale Monza',
        id: 'monza',
        latitude: 45.6208,
        length: 5793,
        longitude: 9.2899,
        name: 'Monza',
        official_name: 'Autodromo Nazionale Monza',
        opened: 1922,
        place_name: 'Monza, Italy',
        shortName: 'Monza',
        timezone: {
            name: 'Europe/Rome',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza',
    },
    shanghai: {
        altitude: 14,
        bbox: [121.214959, 31.335826, 121.227856, 31.345484],
        circuitType: 'RACE',
        country: 'china',
        firstgp: 2004,
        full_name: 'Shanghai International Circuit',
        id: 'shanghai',
        latitude: 31.3389,
        length: 5451,
        longitude: 121.2205,
        name: 'Shanghai',
        official_name: 'Shanghai International Circuit',
        opened: 2004,
        place_name: 'Shanghai, China',
        shortName: 'Shanghai',
        timezone: {
            name: 'Asia/Shanghai',
            offset: 8,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Shanghai_International_Circuit',
    },
    silverstone: {
        altitude: 196,
        bbox: [-1.024286, 52.063513, -1.009264, 52.078936],
        circuitType: 'RACE',
        country: 'united-kingdom',
        firstgp: 1950,
        full_name: 'Silverstone Circuit',
        id: 'silverstone',
        latitude: 52.0786,
        length: 5891,
        longitude: -1.0169,
        name: 'Silverstone',
        official_name: 'Silverstone Circuit',
        opened: 1948,
        place_name: 'Silverstone, United Kingdom',
        shortName: 'Silverstone',
        timezone: {
            name: 'Europe/London',
            offset: 0,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Silverstone_Circuit',
    },
    'spa-francorchamps': {
        altitude: 413,
        bbox: [5.959602, 50.427678, 5.97756, 50.446217],
        circuitType: 'RACE',
        country: 'belgium',
        firstgp: 1950,
        full_name: 'Circuit de Spa-Francorchamps',
        id: 'spa-francorchamps',
        latitude: 50.4372,
        length: 7004,
        longitude: 5.9714,
        name: 'Spa Francorchamps',
        official_name: 'Circuit de Spa-Francorchamps',
        opened: 1925,
        place_name: 'Stavelot, Belgium',
        shortName: 'Spa Francorchamps',
        timezone: {
            name: 'Europe/Brussels',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps',
    },
    spielberg: {
        altitude: 721,
        bbox: [14.754069, 47.219284, 14.770648, 47.226388],
        circuitType: 'RACE',
        country: 'austria',
        firstgp: 1970,
        full_name: 'Red Bull Ring',
        id: 'spielberg',
        latitude: 47.2197,
        length: 4318,
        longitude: 14.7644,
        name: 'Spielberg',
        official_name: 'Red Bull Ring',
        opened: 1969,
        place_name: 'Spielberg, Austria',
        shortName: 'Spielberg',
        timezone: {
            name: 'Europe/Vienna',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Red_Bull_Ring',
    },
    suzuka: {
        altitude: 60,
        bbox: [136.521928, 34.838956, 136.543422, 34.848374],
        circuitType: 'RACE',
        country: 'japan',
        firstgp: 1987,
        full_name: 'Suzuka International Racing Course',
        id: 'suzuka',
        latitude: 34.8431,
        length: 5807,
        longitude: 136.5419,
        name: 'Suzuka',
        official_name: 'Suzuka International Racing Course',
        opened: 1962,
        place_name: 'Suzuka, Japan',
        shortName: 'Suzuka',
        timezone: {
            name: 'Asia/Tokyo',
            offset: 9,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Suzuka_International_Racing_Course',
    },
    'yas-marina': {
        altitude: 9,
        bbox: [54.601568, 24.463158, 54.609556, 24.478648],
        circuitType: 'RACE',
        country: 'united-arab-emirates',
        firstgp: 2009,
        full_name: 'Yas Marina Circuit',
        id: 'yas-marina',
        latitude: 24.4672,
        length: 5281,
        longitude: 54.6031,
        name: 'Yas Marina',
        official_name: 'Yas Marina Circuit',
        opened: 2009,
        place_name: 'Yas Island, Abu Dhabi, United Arab Emirates',
        shortName: 'Abu Dhabi',
        timezone: {
            name: 'Asia/Dubai',
            offset: 4,
            dst: false,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Yas_Marina_Circuit',
    },
    zandvoort: {
        altitude: 3,
        bbox: [4.538742, 52.384363, 4.553061, 52.391811],
        circuitType: 'RACE',
        country: 'netherlands',
        firstgp: 1952,
        full_name: 'Circuit Zandvoort',
        id: 'zandvoort',
        latitude: 52.3885,
        length: 4259,
        longitude: 4.5426,
        name: 'Zandvoort',
        official_name: 'Circuit Zandvoort',
        opened: 1948,
        place_name: 'Zandvoort, Netherlands',
        shortName: 'Zandvoort',
        timezone: {
            name: 'Europe/Amsterdam',
            offset: 1,
            dst: true,
            start: {
                month: 3,
                day: 1,
                hour: 0,
            },
            end: {
                month: 10,
                day: 1,
                hour: 0,
            },
        },
        wiki: 'https://en.wikipedia.org/wiki/Circuit_Zandvoort',
    },
};

export const CIRCUITS = Object.keys(CIRCUIT_DETAILS).map((key) => key);
